version: '2'
services:
  influx:
    image: influxdb
    ports:
      - "8086:8086"
#  chronograf:
#      image: chronograf
#      ports:
#        - "8888:8888"
  rabbitmq:
    build: .
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
